CREATE TABLE USERS (
    USERNAME    VARCHAR(10)    NOT NULL,
    PASSWORD    VARCHAR(32)    NOT NULL,
    ENABLED     SMALLINT,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES (
    USERNAME    VARCHAR(10)    NOT NULL,
    AUTHORITY   VARCHAR(10)    NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS
);

